# Generated by Django 4.1.2 on 2023-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soniablog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
