# Generated by Django 4.1.2 on 2023-01-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soniablog', '0002_alter_subscribedusers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
